import type { Config } from "tailwindcss";

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#b9cacb',
        'primary': '#dbfcff',
        'primary-fixed': '#7df4ff',
        'primary-fixed-dim': '#00dbe9',
        'primary-container': '#00f0ff',
        'on-primary': '#00363a',
        'on-primary-container': '#006970',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'secondary': '#4edea3',
        'secondary-fixed-dim': '#4edea3',
        'secondary-container': '#00a572',
        'on-secondary': '#003824',
        'on-secondary-container': '#00311f',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#f3f6ff',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary': '#213145',
        'on-tertiary-container': '#506076',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-tint': '#00dbe9',
        'outline': '#849495',
        'outline-variant': '#3b494b',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#006970',
      },
      fontFamily: {
        'geist': ['Geist', 'sans-serif'],
        'jetbrains': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-base': ['Geist', 'sans-serif'],
        'status-pill': ['Geist', 'sans-serif'],
        'code-editor': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'status-pill': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-editor': ['14px', { lineHeight: '1.7', letterSpacing: '0em', fontWeight: '450' }],
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
    },
  },
};
